### ISSUE TITLE
Ignore quotes in for column

### ISSUE THREAD

**Issue by eripey** [digital-preservation/csv-validator#149] opened 2017-08-29 14:53 UTC
@totalColumns 20
@separator '|'
@noHeader

above is my directives, I am running into a problem with some of my columns that have quotes in them.  I have tried the character literal for the separator directive http://digital-preservation.github.io/csv-schema/csv-schema-1.1.html#dfn-ebnf-character-literal

doesn't seem to like it.

[3.12] failure: `'' expected but `"' found

@separator "'" [|^\r\n\f'] "'"

Can anyone suggest?

**Comment by DavidUnderdown** [comment] 2017-08-29 15:14
[RFC4180](https://tools.ietf.org/html/rfc4180) specifies that quotes must be escaped with \ if you want a literal quote character within a CSV file.

The field separator is completely separate and specifies an alternative to the use of a comma to separate individual fields.

**Comment by eripey** [comment] 2017-08-29 16:16
I have a file file that is csv by a vertical bar or pipe.   There are some columns  in a record that have one double quote in them and that's what is causing the fail.   This file was generated by another person/company with about 3 million rows.

I was wondering what kind of syntax I can use in the separator to have ignore the any double quotes to prevent in the field.

**Comment by DavidUnderdown** [comment] 2017-08-30 08:33
In essence it's not valid CSV I'm afraid, double quotes should be escaped.  even if the @quoted directive was fully implemented in the validator currently that's not what it's designed to deal with.  This wasn't a use case we considered I'm afraid.

**Comment by eripey** [comment] 2017-08-30 13:00
Okay, thank you for answering.

**Comment by adamretter** [comment] 2017-09-01 13:36
@eripey You could pre-process your CSV with sed or similar to get it into a more standard format for the CSV validator.

**Comment by eripey** [comment] 2017-09-01 13:45
Can you tell me more about sed?

Sent from Outlook<https://aka.ms/qtex0l>
________________________________

**Comment by adamretter** [comment] 2017-09-01 14:00
@eripey nope, but the Web can - https://en.wikipedia.org/wiki/Sed

**Comment by eripey** [comment] 2017-09-01 14:19
Thanks. I appreciate the help.

Sent from Outlook<https://aka.ms/qtex0l>
________________________________

**Comment by eripey** [comment] 2017-09-05 15:10
Okay, I was reading the RFC for the double quotes on page 3, If double-quotes are used to enclose fields, then a double-quote
       appearing inside a field must be escaped by preceding it with
       another double quote.

I don't see anywhere about using \ as the escape.  I tried it  in the document \" but it still didn't work.  How am I supposed to the the escape character \  ?

**Comment by DavidUnderdown** [comment] 2017-09-05 15:33
Sorry, I thought that both \" and "" were valid ways of escaping a quote character, but it looks like you're right per the spec.  I suspect that most CSV processing libraries would recognise either though.  Basically you need to replace any occurrence of " that should literally be that with either \" or "", so using your example above it should look like:

First field value| this is the ""Second Value | Need to ignore the First quote"" for third column | This is the fourth column

or:

First field value| this is the \"Second Value | Need to ignore the First quote\" for third column | This is the fourth column

**Comment by eripey** [comment] 2017-09-05 16:01
I tried the Second example and it didn't like the example usage.  I am now trying your first example.

**Comment by spectramedix** [comment] 2018-08-30 17:47
Hi, I want to identify the column strings which are present in the double quotes.
for ex: in my csv file i have values like a,"a",b,"b"..... under the column Id .
I need a regex to identify columns which are only in the double quotes or viceversa..
Please help me with this.......my formula is regex("\".*\"")  which will give error if values are not in double quotes.

**Comment by spectramedix** [comment] 2018-08-30 19:15
ID: regex("\".*\"")  i have tried using this formula along with regex("^".*"$") and other ways too....

**Comment by DavidUnderdown** [comment] 2018-08-31 07:55
As explained above, you need to escape your quote marks by preceding them with \ - typically quotemarks simply around a field will be ignored by CSV processors - they just confirm that the field contents is text, and that any commas in text between quotes should not be treated as a field separator.

**Comment by spectramedix** [comment] 2018-08-31 15:38
Thanks for the above explanation, it helped me to solve only one scenario but for the below scenario it doesn't work,
Scenario: ID: "a","b",c,"d",e,"f" ------ I need to raise an exception for the column ID to the values c,e which doesn't has double quotes.
Ideally this regex should work but it is not ----> ID : regex("^".*"$"). Please suggest

**Comment by DavidUnderdown** [comment] 2018-08-31 15:45
The problem is CSV Parsers don't tend to see any difference between "c" and c due to the way the RFC defines the CSV standard.  The two things are entirely interchangeable so far as CSV is concerned. It would only work if the quotes in the CSV file itself were escaped, or possibly if we had implemented the quoted directive fully, allowing you to change the quote character to something else.

**Comment by spectramedix** [comment] 2018-09-19 18:42
I want to fail the cases when the values has extra quotes between them. i.e,, i want to fail these below value
"abc"bva" -- which has unwanted quotes. I am attaching my files please check and help with a rule.
[fail_quotes.zip](https://github.com/digital-preservation/csv-validator/files/2398341/fail_quotes.zip)

**Comment by DavidUnderdown** [comment] 2018-09-25 09:12
"abc"bva" should not even be valid in a CSV file, the parser should trip on that, the middle quote (ie after c) would need to be escaped.

**Comment by afranke** [comment] 2019-02-19 14:18
> "abc"bva" should not even be valid in a CSV file, the parser should trip on that, the middle quote (ie after c) would need to be escaped.

While I agree, it’s worth noting that LibreOffice Calc won’t trip on that and they only seem to care about separators. Resilience is valuable.

**Comment by DavidUnderdown** [comment] 2019-02-19 14:31
Yes (see Postel's Law), but it's ambiguous, the software author has to make a decision how to handle cases which don't meet the spec.  Here our decision is to flag the deviation from the spec and get the input fixed because we are specifically doing validation against the spec.

**Comment by DavidUnderdown** [comment] 2022-02-09 10:28
Closing this old call as original poster was happy following discussion

**Closed by DavidUnderdown** 2022-02-09 10:28 UTC
Labels: question
