### ISSUE TITLE
UniqueMulti rule does not report the error correctly

### ISSUE THREAD

**Issue by axos88-da** [digital-preservation/csv-validator#300] opened 2021-05-26 07:11 UTC
It reports `unique(` without listing the columns.

```
col1: regex("\d{1,35}") and unique($col1,$col2)
```

reports the error as: ```regex("\d{1,35}") and unique(```

**Comment by DavidUnderdown** [comment] 2022-02-09 10:03
This actually appears to be a duplicate of #84

**Closed by DavidUnderdown** 2022-02-09 10:03 UTC
Labels: bug, duplicate
