### ISSUE TITLE
Encoding error

### ISSUE THREAD

**Issue by maikpf** [digital-preservation/csv-validator#145] opened 2017-03-27 09:38 UTC
UTF-8 encoded schema get errors on umlaut e.g. 'ä'.
```version 1.1
@separator ';'
@totalColumns 107
extern_id: unique and regex("^\S$|^(\S.{0,198}\S)$")
an_vname: regex("^\S$|^(\S.{0,254}\S)$")
an_name: regex("^\S$|^(\S.{0,254}\S)$")
an_gebname: regex("^\S$|^(\S.{0,254}\S)$") @optional
an_gebdat: regex("^(0[1-9]|[12][0-9]|3[01])[.](0[1-9]|1[012])[.]((19[5-9][0-9])|(20([0-4][0-9])|2050))$")
an_gebort: regex("^\S$|^(\S.{0,254}\S)$") @optional
an_geschlecht: is("männl.") or is("weibl.") // any("männl.","weibl.")
...
```
Output is:
```
[ERROR] is("m�nnl.") or is("weibl.") fails for line: 470, column: an_geschlecht, value: "männl."
```
All files UTF-8 encoded and loaded by java.io.Reader with charset name parameter.

**Comment by DavidUnderdown** [comment] 2017-03-28 09:29
Thank you, we will take a look

**Comment by DavidUnderdown** [comment] 2017-03-28 15:19
I'm afraid we cannot reproduce this.  I've tried gui versions 1.1.2 and 1.1.5 with a minimal schema ie

version 1.1
>an_geschlecht: any("männl.","weibl.")// is("männl.") or is("weibl.") 

and csv file:
>an_geschlecht
>männl.
>weibl.

and validation is successful.

Can you give anymore information about your environment (operating system, gui or command line etc)

**Comment by DavidUnderdown** [comment] 2017-06-13 08:57
As we've been unable to reproduce this, and haven't had any additional info I'm going to close this

**Closed by DavidUnderdown** 2017-06-13 08:57 UTC
Labels: bug, invalid
